SELECT 
    T.FLAVOR
FROM (
    SELECT
        FH.FLAVOR,
        FH.TOTAL_ORDER + COALESCE(SUM(J.TOTAL_ORDER), 0) AS TOTAL_ORDER_SUM
    FROM
        FIRST_HALF FH
    JOIN 
        JULY J 
    ON 
        FH.FLAVOR = J.FLAVOR
    GROUP BY 
        FH.FLAVOR
) AS T
ORDER BY 
    TOTAL_ORDER_SUM DESC
LIMIT 3;
